In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.corpus import stopwords
import pandas as pd
import string
import nltk

In [ ]:
df=pd.read_csv("Reviews.csv")

In [ ]:
df = df[['Score', 'Text']]

In [ ]:
df['Score'].fillna(df['Score'].mean(), inplace=True)

/tmp/ipykernel_4330/3309281762.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].fillna(df['Score'].mean(), inplace=True)

In [ ]:
df.isnull().sum()

Score    0
Text     1
dtype: int64

In [ ]:
df = df.dropna(subset=['Text'])

In [ ]:
df.isnull().sum()

Score    0
Text     0
dtype: int64

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import pandas as pd
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(Text):
    if pd.isna(Text):
        return []


    Text = Text.strip()


    translator = str.maketrans('', '', string.punctuation)
    Text = Text.translate(translator)


    Text = Text.lower()


    tokens = nltk.word_tokenize(Text)


    tokens = [word for word in tokens if word not in stop_words]


    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return tokens


df['processed_text'] = df['Text'].apply(preprocess_text)

df.head()

,Score,Text,processed_text
0,5.0,I have bought several of the Vitality canned d...,"[bought, several, vitality, canned, dog, food,..."
1,1.0,Product arrived labeled as Jumbo Salted Peanut...,"[product, arrived, labeled, jumbo, salted, pea..."
2,4.0,This is a confection that has been around a fe...,"[confection, around, century, light, pillowy, ..."
3,2.0,If you are looking for the secret ingredient i...,"[looking, secret, ingredient, robitussin, beli..."
4,5.0,Great taffy at a great price. There was a wid...,"[great, taffy, great, price, wide, assortment,..."

In [ ]:
clean_sentences = df['processed_text'].apply(lambda x: ' '.join(x))

In [ ]:
tfidf=TfidfVectorizer(stop_words='english')
X=tfidf.fit_transform(clean_sentences)

In [ ]:
y = df['Score']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)